require "ExpandedHelicopter02a_Presets"
require "ExpandedHelicopter09_EasyConfigOptions"

AshenTwitchEvents = AshenTwitchEvents or {}
AshenTwitchEvents.HelpTheStreamer = {}
AshenTwitchEvents.TrollTheStreamer = {}
AshenTwitchEvents.TWE_Airevents = {}
AshenTwitchEvents.TWETraitsTable = {}
AshenTwitchEvents.roll20Gift = ""
AshenTwitchEvents.enableAI = true
AshenTwitchEvents.hordeZedQnt = 7
AshenTwitchEvents.client = AshenTwitchEvents.client or {}

local timervalue = 10 --timer value in minutes for the temporary traits
local TWE_Events = {}
local TraitEndTime = 0
local ViewerName = ""
----positive items table
local HelpTheStreamer ={ "Base.BaseballBat", "Base.HuntingKnife", "Base.Axe", "Base.WristWatch_Right_DigitalRed", "Base.Crowbar", "Base.HandAxe", "Base.Burger", "Base.Crisps", "Base.Sandwich", "Base.BeerBottle", "Base.Pop","Base.Belt2","Base.TinnedBeans" }
----negative items table
local TrollTheStreamer = { "Base.Generator", "Base.LogStacks4", "Base.Dirtbag", "Base.Sandbag" }
-----Air Events Presets
local TWE_Airevents = {"military","police","news_chopper_hover","raiders","FEMA_drop","jet","survivor_heli","military_attackhelicopter_zombies","samaritan_drop"}
-----Temporary traits table
local TWETraitsTable = {[1]="Deaf",[2]="Thinskinned",[3]="AllThumbs",[4]="Cowardly",[5]="Hemophobic",[6]="SundayDriver",[7]="Graceful",[8]="KeenHearing",[9]="ThickSkinned",[10]="SpeedDemon",[11]="Jogger",[12]="Inconspicuous"}
local TWETempTraitsTable = {}
local TWEAnnouceEvents = true
local playerChar = getPlayer()
local LocalEventsTable = {}
-- create local table temporaryZombies
local temporaryZombies = {}
local temporaryZombiesEnd = 0

local ClientCommands = {};
ClientCommands.AshenTwitch = {}
local ServerCommands = {};
ServerCommands.AshenTwitch = {}

--processes the EventsTable generated by getreward
-- function performHandshake(EventsTable)
AshenTwitchEvents.client.performHandshake = function(EventsTable)
    local playerChar = getPlayer()
	-- LocalEventsTable = EventsTable
	-- print(playerChar:getUsername())
	ServerEvent = {["Etype"] = "Handshake", ["ZedX"] = Zedx, ["ZedY"] = Zedy, ["ZedQ"] = zedquant, ["target"] = playerchar, ["EventsTable"] = EventsTable}
	ServerEvent.state = "Request"
	ServerEvent.initiator = playerChar:getUsername()
	--playerChar:Say("x:" .. tostring(ServerEvent.ZedX) .. "y: " .. tostring(ServerEvent.ZedY))
	if isClient() then
		sendClientCommand("AshenTwitch", "Handshake", ServerEvent) -- Trigger Event from Client to Server
	else
		AshenTwitchEvents.client.performEvent(ServerEvent.EventsTable, ServerEvent.initiator)
	end
end

-- function getSandbox()
AshenTwitchEvents.client.getSandbox = function()
	local helpString = SandboxVars.AshenTwitchEvents.HelpTheStreamer
	-- this is a string containing item names, separated by ;
	-- we neet to split it into a table
	AshenTwitchEvents.HelpTheStreamer = {}
	for item in helpString:gmatch("([^;]+)") do
		table.insert(AshenTwitchEvents.HelpTheStreamer, item)
	end

	-- repeat for other settings
	local trollString = SandboxVars.AshenTwitchEvents.TrollTheStreamer
	AshenTwitchEvents.TrollTheStreamer = {}
	for item in trollString:gmatch("([^;]+)") do
		table.insert(AshenTwitchEvents.TrollTheStreamer, item)
	end
	
	local aireventsString = SandboxVars.AshenTwitchEvents.TWE_Airevents
	AshenTwitchEvents.TWE_Airevents = {}
	for item in aireventsString:gmatch("([^;]+)") do
		table.insert(AshenTwitchEvents.TWE_Airevents, item)
	end

	local traitsString = SandboxVars.AshenTwitchEvents.TWETraitsTable
	AshenTwitchEvents.TWETraitsTable = {}
	for item in traitsString:gmatch("([^;]+)") do
		table.insert(AshenTwitchEvents.TWETraitsTable, item)
	end

	AshenTwitchEvents.roll20Gift = SandboxVars.AshenTwitchEvents.roll20Gift
	AshenTwitchEvents.enableAI = SandboxVars.AshenTwitchEvents.enableAI
	AshenTwitchEvents.hordeZedQnt = SandboxVars.AshenTwitchEvents.hordeZedQnt
end

-- function performAAIevent(event)
AshenTwitchEvents.client.performAAIevent = function(event)
	local playerChar = getSpecificPlayer(0)

	if #AshenTwitchEvents.TWETraitsTable == 0 then
		getSandbox()
	end

	if event.type == 'zombie_spawn' then
		local zedquant = event.zedquant
		local zedpacks = event.zedpacks

		local message = "ZombieMaster Ashen ti manda "
		if event.from then 
			message ="Il roll di " .. event.from .. " ti manda "
		end
		if not event.horde and not event.from then
			playerChar:Say("Sei troppo rilassato!!")
		end
		if zedpacks == 1 then
			if zedquant == 1 then
				message = message .. zedquant .. " zombie"
			else
				message = message .. zedquant .. " zombies"
			end
		else
			message = message .. zedpacks .. "x" .. zedquant .. " zombies (" .. zedquant * zedpacks .. ")"
		end
		if event.toothless or event.runner then 
			if event.runner then
				message = message .. ' [CORRIDORE]'
			end
			if event.toothless then
				message = message .. ' [SENZA DENTI]'
			end
		end
		playerChar:Say(message)
		if AshenTwitchEvents.Options.playSounds then
			-- audio selection
			if event.horde then
				playerChar:playSound("Allarme")
			elseif event.runner then
				playerChar:playSound("Maiale")
			else
				playerChar:playSound("Winter")
			end
		end

		if isClient() then
			for i=1, zedpacks do
				local radius = event.radius or 15
				local Zedx, Zedy, Zedz = AshenTwitchEvents.client.SpawnLoc(playerChar, radius)
				ServerEvent = {["Etype"] = "Zedspawn", ["ZedX"] = Zedx, ["ZedY"] = Zedy, ["ZedQ"] = zedquant, ["viewer"] = "AAI", ["PlayerChar"] = playerchar, ["radius"] = 30 }
				ServerEvent["runner"] = event.runner
				ServerEvent["toothless"] = event.toothless
				--playerChar:Say("x:" .. tostring(ServerEvent.ZedX) .. "y: " .. tostring(ServerEvent.ZedY))
				-- print("CLIENT| spawning pack of " .. zedquant .. " zeds at " .. Zedx .. " " .. Zedy .. " " .. Zedz .. " zedpack #" .. i)
				sendClientCommand("AshenTwitch", "Zedspawn", ServerEvent); -- Trigger Event from Client to Server
			end
		else
			for i=1, zedpacks do
				local radius = event.radius or 15
				Zedx, Zedy, Zedz = AshenTwitchEvents.client.SpawnLoc(playerChar, radius)
				print("spawning pack of " .. zedquant .. " zeds at " .. Zedx .. " " .. Zedy .. " " .. Zedz .. " zedpack #" .. i)
				if event.toothless or event.runner then 
					generated_event = {["X"] = Zedx, ["Y"] = Zedy, ["Z"] = Zedz, ["radius"] = 30, ["player"] = playerChar, ["viewer"] = "AAI", ["zedquant"] = zedquant}
					generated_event["runner"] = event.runner
					generated_event["toothless"] = event.toothless
					-- spawnSpecificZombie(generated_event)
					AshenTwitchEvents.client.spawnSpecificZombie(generated_event)
				else
					createHordeFromTo(Zedx, Zedy, playerChar:getX(), playerChar:getY(), zedquant)
				end
			end
		end
	elseif event.type == "gift" then
		ViewerName = "ZombieMaster Ashen"
		if AshenTwitchEvents.Options.playSounds then
			event.player:playSound("Drum")
		end
		TWE_Events.GiftItems(event)
	end
end

-- function eventMessageFiller(event)
AshenTwitchEvents.client.eventMessageFiller = function(event)
	if not event.gifts then
		event.gifts = 0
	end
	if not event.trait then
		event.trait = 0
	end
	if not event.helicopter then
		event.helicopter = 0
	end
	if not event.zombie_modifier then
		event.zombie_modifier = 0
	end
	if not event.player_modifier then
		event.player_modifier = 0
	end
	if not event.jumpscare then
		event.jumpscare = 0
	end

	return event
end

-- function performEvent(EventsTable, initiator)
AshenTwitchEvents.client.performEvent = function(EventsTable, initiator)
	-- setActivePlayer(0)
	local playerChar = getSpecificPlayer(0)
	local playerRemote = getSpecificPlayer(1)
	local username = playerChar:getUsername()

	if #AshenTwitchEvents.TWETraitsTable == 0 then
		AshenTwitchEvents.client.getSandbox()
	end

	EventsTable = AshenTwitchEvents.client.eventMessageFiller(EventsTable)

	if EventsTable then
		ViewerName = EventsTable["Viewer"]
		if EventsTable["rolledEvent"] then
			AshenTwitchEvents.client.performRolledEvent(EventsTable)
		end

		if EventsTable["ringoffire"] then
			event = {}
			event.player = playerChar
			event.radius = 10
			event.points = 8
			local message = EventsTable["Viewer"] .. ' crea un muro di fuoco attorno a te!'
			playerChar:Say(message)
			if AshenTwitchEvents.Options.playSounds then
				playerChar:playSound("Tatataaa")
			end
			if isClient() then
				sendClientCommand("AshenTwitch", "RingofFire", event)
			else
				AshenTwitchEvents.client.ringOfFire(event)
			end
		end

		if EventsTable["revivezombies"] then
			event = {}
			event.player = playerChar
			event.range = EventsTable["range"] or 10
			local message = EventsTable["Viewer"] .. ' resuscita i morti!'
			playerChar:Say(message)
			if AshenTwitchEvents.Options.playSounds then
				playerChar:playSound("Leeroy")
			end
			if isClient() then
				sendClientCommand("AshenTwitch", "ReviveZombies", event)
			else
				AshenTwitchEvents.client.reviveZombies(event)
			end
		end

		if EventsTable["zombies"] == true and EventsTable["zedquant"] > 0 then
			-- print("------------=Twitch Events: zombies=------------")
			if TWEAnnouceEvents == true then
				-- audio selection
				if EventsTable["timedZombies"] then
					if AshenTwitchEvents.Options.playSounds then
						playerChar:playSound("Benny")
					end
					local calendar = PZCalendar.getInstance()
					temporaryZombiesEnd = calendar:getTimeInMillis() + 25000
					Events.EveryOneMinute.Add(TWE_Events.ZombieModifierEnd)
				elseif EventsTable["runner"] and AshenTwitchEvents.Options.playSounds then
					playerChar:playSound("Maiale")
				elseif AshenTwitchEvents.Options.playSounds then
					playerChar:playSound("Winter")
				end

				if EventsTable["zedpacks"] > 1 then
					local message = EventsTable["Viewer"] .. getText("UI_ZombieSpawn") .. EventsTable["zedpacks"] .. getText("UI_ZombiePacks")
					message = message .. EventsTable["zedquant"] .. " zombies (" .. EventsTable["zedquant"] * EventsTable["zedpacks"] .. ")"
					if EventsTable["toothless"] or EventsTable["runner"] then 
						if EventsTable["runner"] then
							message = message .. ' [CORRIDORE]'
						end
						if EventsTable["toothless"] then
							message = message .. ' [SENZA DENTI]'
						end
					end
					playerChar:Say(message)
					if playerRemote then
						playerRemote:Say(message)
					end
				else
					local message = EventsTable["Viewer"] .. getText("UI_ZombieSpawn") .. EventsTable["zedquant"] .. " zombies"
					if EventsTable["toothless"] or EventsTable["runner"] then 
						if EventsTable["runner"] then
							message = message .. ' [CORRIDORI]'
						end
						if EventsTable["toothless"] then
							message = message .. ' [SENZA DENTI]'
						end
					end
					playerChar:Say(message)
					if playerRemote then
						playerRemote:Say(message)
					end
				end

				if initiator ~= username then
					args = {}
					args.message = username .. getText("UI_ZombieAttacts") .. EventsTable["zedquant"] * EventsTable["zedpacks"] .. " zombies"
					args.initiator = initiator
					sendClientCommand("AshenTwitch", "ForwardMessage", args)
				end
			end

			-- OLD way spawn only on initiator
			-- if initiator == playerChar:getUsername() then
			-- removed for TMP42 fix
			-- if AshenTwitchEvents.Options.acceptEvents or playerChar:getUsername() == args.initiator then
			if true then
				--local Zedx, Zedy, wz = LSpawnLoc();
				local zedquant = tonumber(EventsTable["zedquant"])
				if isClient() then
					for i=1, EventsTable["zedpacks"] do
						local radius = EventsTable["radius"] or 30
						local Zedx, Zedy, Zedz = AshenTwitchEvents.client.SpawnLoc(playerChar, radius)
						ServerEvent = {["Etype"] = "Zedspawn", ["ZedX"] = Zedx, ["ZedY"] = Zedy, ["ZedQ"] = zedquant, ["PlayerChar"] = playerchar }
						ServerEvent["runner"] = EventsTable["runner"]
						ServerEvent["toothless"] = EventsTable["toothless"]
						ServerEvent["timedZombies"] = EventsTable["timedZombies"]
						--playerChar:Say("x:" .. tostring(ServerEvent.ZedX) .. "y: " .. tostring(ServerEvent.ZedY))
						print("CLIENT| spawning pack of " .. zedquant .. " zeds at " .. Zedx .. " " .. Zedy .. " " .. Zedz .. " zedpack #" .. i)
						sendClientCommand("AshenTwitch", "Zedspawn", ServerEvent); -- Trigger Event from Client to Server
					end
					
					-- local Zedx, Zedy, Zedz = SpawnLoc(50)
					-- ServerEvent = {["Etype"] = "Zedspawn", ["ZedX"] = Zedx, ["ZedY"] = Zedy, ["ZedQ"] = zedquant, ["PlayerChar"] = playerchar }
					-- --playerChar:Say("x:" .. tostring(ServerEvent.ZedX) .. "y: " .. tostring(ServerEvent.ZedY))
					-- sendClientCommand("AshenTwitch", "Zedspawn", ServerEvent); -- Trigger Event from Client to Server
				else
					for i=1, EventsTable["zedpacks"] do
						local radius = EventsTable["radius"] or 30
						Zedx, Zedy, Zedz = AshenTwitchEvents.client.SpawnLoc(playerChar, radius)
						if playerRemote then
							RZedx, RZedy, RZedz = AshenTwitchEvents.client.SpawnLoc(playerRemote, radius)
						end
						print("spawning pack of " .. zedquant .. " zeds at " .. Zedx .. " " .. Zedy .. " " .. Zedz .. " zedpack #" .. i)
						if EventsTable["toothless"] or EventsTable["runner"] then 
							event = {["X"] = Zedx, ["Y"] = Zedy, ["Z"] = Zedz, ["radius"] = radius, ["player"] = playerChar, ["viewer"] = ViewerName, ["zedquant"] = zedquant}
							event["runner"] = EventsTable["runner"]
							event["toothless"] = EventsTable["toothless"]
							local zombieLocalTmp = AshenTwitchEvents.client.spawnSpecificZombie(event)
							local zombieRemoteTmp = nil
							if playerRemote then
								event.X = RZedx
								event.Y = RZedy
								event.Z = RZedz
								event["player"] = playerRemote
								zombieRemoteTmp = AshenTwitchEvents.client.spawnSpecificZombie(event)
							end

							if EventsTable["timedZombies"] then
								if zombieLocalTmp then
									for i=0, zombieLocalTmp:size()-1 do
										-- kill the zombie
										zombie = zombieLocalTmp:get(i)
										table.insert(temporaryZombies, zombie)
										-- zombie:removeFromWorld()
									end
								end
								if zombieRemoteTmp then
									for i=0, zombieRemoteTmp:size()-1 do
										-- kill the zombie
										zombie = zombieRemoteTmp:get(i)
										table.insert(temporaryZombies, zombie)
										-- zombie:removeFromWorld()
									end
								end
							end
						else
							createHordeFromTo(Zedx, Zedy, playerChar:getX(), playerChar:getY(), zedquant)
							if playerRemote then
								createHordeFromTo(RZedx, RZedy, playerRemote:getX(), playerRemote:getY(), zedquant)
							end
						end
					end
				end
			end
		end

		if tonumber(EventsTable["gifts"]) > 0 then
			-- print("------------=Twitch Events: gift =------------")
			if AshenTwitchEvents.Options.playSounds then
				playerChar:playSound("Drum")
			end
			event = {}
			event.player = playerChar
			event.initiator = initiator
			event.whatkind = tonumber(EventsTable["gifts"])
			if EventsTable["itemid"] then 
				event.itemid =tonumber(EventsTable["itemid"])
			end
			TWE_Events.GiftItems(event)
			if playerRemote then
				event.player = playerRemote
				TWE_Events.GiftItems(event)
			end
		end

		if tonumber(EventsTable["helicopter"]) > 0 then

			if tonumber(EventsTable["helicopter"]) == 1 then
				print("------------=Twitch Events: Air Event=------------")
				if TWEAnnouceEvents == true then
					playerChar:Say(EventsTable["Viewer"] .. getText("UI_AirEventMilitary"))
				end

				if initiator == playerChar:getUsername() then
					if isClient() then
						ServerEvent = {["Etype"] = "AirEvent", ["target"] = playerchar, ["Event"] = "military" }
						sendClientCommand("AshenTwitch", "AirEvent", ServerEvent); -- Trigger Event from Client to Server
					else
						local heli = getFreeHelicopter("military")
						heli:launch(playerChar, false)
					end
				end
			end

			if tonumber(EventsTable["helicopter"]) == 2 then
				print("------------=Twitch Events: Air Event=------------")
				if TWEAnnouceEvents == true then
					playerChar:Say(EventsTable["Viewer"] .. getText("UI_AirEventNews"))
				end

				if initiator == playerChar:getUsername() then
					if isClient() then
						ServerEvent = {["Etype"] = "AirEvent", ["target"] = playerchar, ["Event"] = "news_chopper_hover" }
						sendClientCommand("AshenTwitch", "AirEvent", ServerEvent); -- Trigger Event from Client to Server
					else
						local heli = getFreeHelicopter("news_chopper_hover")
						heli:launch(playerChar, false)
					end
				end
			end

			if tonumber(EventsTable["helicopter"]) == 3 then
				print("------------=Twitch Events: Air Event=------------")
				if TWEAnnouceEvents == true then
					playerChar:Say(EventsTable["Viewer"] .. getText("UI_AirEventPolice"))
				end

				if initiator == playerChar:getUsername() then
					if isClient() then
						ServerEvent = {["Etype"] = "AirEvent", ["target"] = playerchar, ["Event"] = "police" }
						sendClientCommand("AshenTwitch", "AirEvent", ServerEvent); -- Trigger Event from Client to Server
					else
						local heli = getFreeHelicopter("police")
						heli:launch(playerChar, false)
					end
				end
			end

			if tonumber(EventsTable["helicopter"]) == 4 then
				print("------------=Twitch Events: Air Event=------------")
				if TWEAnnouceEvents == true then
					playerChar:Say(EventsTable["Viewer"] .. getText("UI_AirEventRaiders"))
				end
				
				if initiator == playerChar:getUsername() then
					if isClient() then
						ServerEvent = {["Etype"] = "AirEvent", ["target"] = playerchar, ["Event"] = "raiders" }
						sendClientCommand("AshenTwitch", "AirEvent", ServerEvent); -- Trigger Event from Client to Server
					else
						local heli = getFreeHelicopter("raiders")
						heli:launch(playerChar, false)
					end
				end
			end

			if tonumber(EventsTable["helicopter"]) == 5 then
				print("------------=Twitch Events: Air Event=------------")
				if TWEAnnouceEvents == true then
					playerChar:Say(EventsTable["Viewer"] .. getText("UI_AirEventFema"))
				end

				if initiator == playerChar:getUsername() then
					if isClient() then
						ServerEvent = {["Etype"] = "AirEvent", ["target"] = playerchar, ["Event"] = "FEMA_drop" }
						sendClientCommand("AshenTwitch", "AirEvent", ServerEvent); -- Trigger Event from Client to Server
					else
						local heli = getFreeHelicopter("FEMA_drop")
						heli:launch(playerChar, false)
					end
				end
			end

			if tonumber(EventsTable["helicopter"]) == 6 then
				print("------------=Twitch Events: Air Event=------------")
				if TWEAnnouceEvents == true then
					playerChar:Say(EventsTable["Viewer"] .. getText("UI_AirEventJet"))
				end

				if initiator == playerChar:getUsername() then
					if isClient() then
						ServerEvent = {["Etype"] = "AirEvent", ["target"] = playerchar, ["Event"] = "jet" }
						sendClientCommand("AshenTwitch", "AirEvent", ServerEvent); -- Trigger Event from Client to Server
					else
						local heli = getFreeHelicopter("jet")
						heli:launch(playerChar, false)
					end
				end
			end

			if tonumber(EventsTable["helicopter"]) == 7 then
				print("------------=Twitch Events: Air Event=------------")
				if TWEAnnouceEvents == true then
					playerChar:Say(EventsTable["Viewer"] .. getText("UI_AirEventMilitaryFriendly"))
				end

				if initiator == playerChar:getUsername() then
					if isClient() then
						ServerEvent = {["Etype"] = "AirEvent", ["target"] = playerchar, ["Event"] = "military_attackhelicopter_zombies" }
						sendClientCommand("AshenTwitch", "AirEvent", ServerEvent); -- Trigger Event from Client to Server
					else
						local heli = getFreeHelicopter("military_attackhelicopter_zombies")
						heli:launch(playerChar, false)
					end
				end
			end

			if tonumber(EventsTable["helicopter"]) == 8 then
				print("------------=Twitch Events: Air Event=------------")
				if TWEAnnouceEvents == true then
					playerChar:Say(EventsTable["Viewer"] .. getText("UI_AirEventSurvivor"))
				end

				if initiator == playerChar:getUsername() then
					if isClient() then
						ServerEvent = {["Etype"] = "AirEvent", ["target"] = playerchar, ["Event"] = "survivor_heli" }
						sendClientCommand("AshenTwitch", "AirEvent", ServerEvent); -- Trigger Event from Client to Server
					else
						local heli = getFreeHelicopter("survivor_heli")
						heli:launch(playerChar, false)
					end
				end
			end

			if tonumber(EventsTable["helicopter"]) == 9 then
				print("------------=Twitch Events: Air Event=------------")
				if TWEAnnouceEvents == true then
					playerChar:Say(EventsTable["Viewer"] .. getText("UI_AirEventSamaritan"))
				end

				if initiator == playerChar:getUsername() then
					if isClient() then
						ServerEvent = {["Etype"] = "AirEvent", ["target"] = playerchar, ["Event"] = "samaritan_drop" }
						sendClientCommand("AshenTwitch", "AirEvent", ServerEvent); -- Trigger Event from Client to Server
					else
						local heli = getFreeHelicopter("samaritan_drop")
						heli:launch(playerChar, false)
					end
				end
			end

			if tonumber(EventsTable["helicopter"]) == 100 then
				print("------------=Twitch Events: Air Event=------------")
				if TWEAnnouceEvents == true then
					playerChar:Say(EventsTable["Viewer"] .. getText("UI_AirEventRandom"))
				end

				if initiator == playerChar:getUsername() then
					if isClient() then
						ServerEvent = {["Etype"] = "AirEvent", ["target"] = playerchar, ["Event"] = "RANDOM" }
						sendClientCommand("AshenTwitch", "AirEvent", ServerEvent); -- Trigger Event from Client to Server
					else
						local heli = getFreeHelicopter("RANDOM")
						heli:launch(playerChar, false)
					end
				end
			end

			if tonumber(EventsTable["helicopter"]) == 69 then
				print("------------=Twitch Events: Custom Air Event=------------")
				if TWEAnnouceEvents == true then
					playerChar:Say(EventsTable["Viewer"] .. " called a ".. EventsTable["title"])
				end

				if initiator == playerChar:getUsername() then
					if isClient() then
						ServerEvent = {["Etype"] = "AirEvent", ["target"] = playerchar, ["Event"] = EventsTable["title"] }
						sendClientCommand("AshenTwitch", "AirEvent", ServerEvent); -- Trigger Event from Client to Server
					else
						local heli = getFreeHelicopter(EventsTable["title"])
						heli:launch(playerChar, false)
					end
				end
			end
			
		end

		local part_modifier = tonumber(EventsTable["part_modifier"])
		if EventsTable["gas"] then --car events begin
			TWE_Events.TWECars(EventsTable["Viewer"], "GasTank", part_modifier)
		end
		if EventsTable["tire"] then
			TWE_Events.TWECars(EventsTable["Viewer"], "FlatTire", part_modifier)
		end
		if EventsTable["muffler"] then
			TWE_Events.TWECars(EventsTable["Viewer"], "Muffler", part_modifier)
		end
		if EventsTable["battery"] then
			TWE_Events.TWECars(EventsTable["Viewer"], "Battery", part_modifier)
		end
		if EventsTable["engine"] then -- car events end
			TWE_Events.TWECars(EventsTable["Viewer"], "Engine", part_modifier)
		end

		if tonumber(EventsTable["trait"]) == 99 then -- random trait
			print("------------=Twitch Events: random trait Event=------------")
			-- get the size of AshenTwitchEvents.TWETraitsTable
			-- get a random number between 1 and the size of AshenTwitchEvents.TWETraitsTable
			local length = 0
			-- TMP B42 FIX
			-- for k, v in pairs(AshenTwitchEvents.TWETraitsTable) do
			
			-- local TWETraitsTable = {[1]="Deaf",[2]="Thinskinned",[3]="AllThumbs",[4]="Cowardly",[5]="Hemophobic",[6]="SundayDriver", [7]="HardHearing", [8]="Illiterate", [9]="Unlucky"}
			for k, v in pairs(AshenTwitchEvents.TWETraitsTable) do
				length = length + 1
			end
			length = length + 1
			if AshenTwitchEvents.Options.playSounds then
				playerChar:playSound("Virus")
			end
			event = {}
			event.player = playerChar
			event.trait = ZombRand(1,length)
			event.initiator = initiator
			AshenTwitchEvents.client.TWETableTraitsTrigger(event)
			if playerRemote then
				event.player = playerRemote
				event.trait = ZombRand(1,length)
				AshenTwitchEvents.client.TWETableTraitsTrigger(event)
			end
		elseif tonumber(EventsTable["trait"]) > 0 then -- specific trait
			print("------------=Twitch Events: specific trait Event=------------")
			if AshenTwitchEvents.Options.playSounds then
				playerChar:playSound("Virus")
			end
			event = {}
			event.player = playerChar
			event.trait = tonumber(EventsTable["trait"])
			event.initiator = initiator
			AshenTwitchEvents.client.TWETableTraitsTrigger(event)
			if playerRemote then
				event.player = playerRemote
				AshenTwitchEvents.client.TWETableTraitsTrigger(event)
			end
		end

		-- zombie modifier
		if tonumber(EventsTable["zombie_modifier"]) > 0 then
			if playerChar:getUsername() == initiator or tonumber(EventsTable["zombie_modifier"]) ~= 2 then
				print("------------=Twitch Events: zombie modifier Event=------------")
				if AshenTwitchEvents.Options.playSounds then
					playerChar:playSound("Evil")
				end
				TWE_Events.ZombieModifier(tonumber(EventsTable["zombie_modifier"]), initiator)
			elseif tonumber(EventsTable["zombie_modifier"]) == 2 then
				if initiator ~= username then
					playerChar:Say(EventsTable["Viewer"] .. " teletrasporta gli zombie!")
				end
			end
		end

		-- player modifier
		if tonumber(EventsTable["player_modifier"]) > 0 then
			-- print("------------=Twitch Events: player modifier Event=------------")
			event = {}
			event.player = playerChar
			event.whatkind = tonumber(EventsTable["player_modifier"])
			event.initiator = initiator
			event.message = EventsTable["message"]
			event.range = EventsTable["range"] or 50
			event.range = EventsTable["range"] or 50
			if AshenTwitchEvents.Options.playSounds then
				playerChar:playSound("Thank")
			end
			TWE_Events.PlayerModifier(event)
			if playerRemote then
				event.player = playerRemote
				TWE_Events.PlayerModifier(event)
			end
		end

		-- jumpscare
		if tonumber(EventsTable["jumpscare"]) > 0 then
			-- print("------------=Twitch Events: jumpscare Event=------------")
			TWE_Events.Jumpscare()
		end
	end
end

-- function reviveZombies(event)
AshenTwitchEvents.client.reviveZombies = function(event)
    local range = event.range or 10
    local player = event.player
    if not player then
        print("ERROR: Player not found.")
        return
    end

    local px, py, pz = player:getX(), player:getY(), player:getZ()
    local cell = player:getCell()

    for dx = -range, range do
        for dy = -range, range do
            local square = cell:getGridSquare(px + dx, py + dy, pz)
            if square then
                local corpses = square:getDeadBodys()
                for i = 0, corpses:size() - 1 do
                    local corpse = corpses:get(i)
                    if not corpse:isSkeleton() then
                        corpse:setReanimateTime(getGameTime():getWorldAgeHours() + (3 / 3600)) -- Reanimate in 3 seconds
                        print("Reviving corpse at (" .. square:getX() .. ", " .. square:getY() .. ", " .. square:getZ() .. ")")
                    end
                end
            end
        end
    end
end

-- function ringOfFire(event)
AshenTwitchEvents.client.ringOfFire = function(event)
	local radius = event.radius or 10
	local points = event.points or 15
	local radius = event.radius or 10
    local points = event.points or 15
	local player = event.player
    if not player then return end
    local playerX = math.floor(player:getX())
    local playerY = math.floor(player:getY())
    local playerZ = math.floor(player:getZ())

    local angleStep = 360 / points
    local seenTiles = {}

    for i = 0, points - 1 do
        local angle = i * angleStep
        local radian = math.rad(angle)
        local tileX = math.floor(playerX + radius * math.cos(radian))
        local tileY = math.floor(playerY + radius * math.sin(radian))
        local key = tileX .. "," .. tileY

        
        if not seenTiles[key] then
            seenTiles[key] = true
            local square = getCell():getGridSquare(tileX, tileY, playerZ)
            if square then
                
                pcall(function()
                    square:explode()
                end)
            end
        end
    end
end

-- function spawnSpecificZombie(event)
AshenTwitchEvents.client.spawnSpecificZombie = function(event)
    local radius =  event.radius or 10
    -- local player = getPlayer()
    if not event.player then
        print("ERROR: Player not found.")
        return
    end

    -- local playerX, playerY, playerZ = player:getX(), player:getY(), player:getZ()
    -- local angle = ZombRandFloat(0, 2 * math.pi)
    -- local distance = ZombRandFloat(0, radius)
    -- local spawnX = playerX + math.cos(angle) * distance
    -- local spawnY = playerY + math.sin(angle) * distance
	local zombieList = ArrayList.new()
	for i=1, event.zedquant do
		local zombie = createZombie(event.X, event.Y, event.Z, nil, 0, IsoDirections.W)
		if zombie then
			if event.runner then
				zombie:setWalkType("sprint1")
			end
			if event.toothless then
				zombie:setNoTeeth(event.toothless)
			end
			zombie:setTarget(event.player)
			zombie:pathToCharacter(event.player)
			zombieList:add(zombie)
		end
	end

	return zombieList
end

--temporary traits trigger---
-- function TWETableTraitsTrigger(event)
AshenTwitchEvents.client.TWETableTraitsTrigger = function(event)
	local playerChar = event.player
	local MyTrait = event.trait
	local initiator = event.initiator
	local username = playerChar:getUsername()
	local calendar = PZCalendar.getInstance()
	local hour = calendar:get(Calendar.HOUR_OF_DAY)
	local minute = calendar:get(Calendar.MINUTE)
	local second = calendar:get(Calendar.SECOND)
	if hour == 0 then --check if its 0, if true replaces 0 with 24
		TraitEndTime = (24 * 60 + minute + timervalue ) * 60 + second
	else 
		TraitEndTime = (hour * 60 + minute + timervalue) * 60 + second
	end	
	
	selectedTrait = AshenTwitchEvents.TWETraitsTable[MyTrait]
	-- if not playerChar:HasTrait(TWETraitsTable[MyTrait]) then
		-- playerChar:getTraits():add(TWETraitsTable[MyTrait]);
		-- table.insert(TWETempTraitsTable, {trait = TWETraitsTable[MyTrait], endtime = TraitEndTime})
		-- HaloTextHelper.addTextWithArrow(playerChar, getText("UI_trait_"..TWETraitsTable[MyTrait]), true, HaloTextHelper.getColorGreen())

	local traitDescr = getText("UI_trait_" .. selectedTrait)
	if selectedTrait == "UI_trait_" .. selectedTrait then
		if selectedTrait == "Thinskinned" then
			traitDescr = getText("UI_trait_ThinSkinned")
		else
			traitDescr = getText("UI_trait_" .. string.lower(selectedTrait))
		end
	end

	if not playerChar:HasTrait(selectedTrait) then
		playerChar:getTraits():add(selectedTrait)
		table.insert(TWETempTraitsTable, {trait = selectedTrait, endtime = TraitEndTime})
		HaloTextHelper.addTextWithArrow(playerChar, traitDescr, true, HaloTextHelper.getColorGreen())

		if initiator ~= username then
			args = {}
			args.message = username .. " ha ricevuto " .. traitDescr
			args.initiator = initiator
			sendClientCommand("AshenTwitch", "ForwardMessage", args)
		end

		Events.EveryOneMinute.Remove(AshenTwitchEvents.client.TWE_TraitCheck)
		Events.EveryOneMinute.Add(AshenTwitchEvents.client.TWE_TraitCheck)
	end

end

--temporary traits timer check---
-- function TWE_TraitCheck()
AshenTwitchEvents.client.TWE_TraitCheck = function()
	local playerChar = getPlayer()
	local calendar = PZCalendar.getInstance()
	local hour = calendar:get(Calendar.HOUR_OF_DAY)
	local minute = calendar:get(Calendar.MINUTE)
	local second = calendar:get(Calendar.SECOND)
	if hour == 0 then --check if its 0, if true replaces 0 with 24
		currentTime = (24 * 60 + minute) * 60 + second
	else 
		currentTime = (hour * 60 + minute) * 60 + second
	end

	for i, v in ipairs(TWETempTraitsTable) do
		local trait = v.trait
		local endtime = v.endtime
		if endtime <= currentTime then
			print("Removing trait: " .. trait)
			print("Endtime: " .. endtime)
			playerChar:getTraits():remove(trait);
			HaloTextHelper.addTextWithArrow(playerChar, getText("UI_trait_"..trait), false, HaloTextHelper.getColorRed())     
			table.remove(TWETempTraitsTable, i)
			if TWETempTraitsTable == 0 then
				Events.EveryOneMinute.Remove(AshenTwitchEvents.client.TWE_TraitCheck)
				break
			end
		end
	end
end

--car event actions
function TWE_Events.TWECars(Viewer, Mypart, modifier)
    local playerChar = getPlayer()
	local mycar = playerChar:getVehicle()
    local TireSet = { "TireRearRight", "TireRearLeft"," TireFrontRight", "TireFrontLeft"}
    local WhichTire = ZombRand(1,5)
    if mycar ~= nil then
        for i = mycar:getPartCount()-1,0,-1 do
            local part = mycar:getPartByIndex(i)
            local cat = part:getCategory()
            local item = part:getId()
            if item ~=  nil then
                if Mypart == "Engine" and item == Mypart then
					local condition = part:getCondition()
					if modifier > 0 then
                    	playerChar:Say(Viewer .. getText("UI_engineBonus") .. " " .. modifier)
					else
                    	playerChar:Say(Viewer .. getText("UI_engineMalus") .. " " .. modifier)
					end
					part:setCondition(condition + modifier)
                end
                if Mypart == "FlatTire" then
                    if TireSet[WhichTire] == item then
                        VehicleUtils.RemoveTire(part, true)
                    end
				end
				if Mypart == "GasTank" and item == Mypart then
					local content = part:getContainerContentAmount()
					if modifier > 0 then
                    	playerChar:Say(Viewer .. getText("UI_gasBonus") .. " " .. modifier)
					else
                    	playerChar:Say(Viewer .. getText("UI_gasMalus") .. " " .. modifier)
					end
					part:setContainerContentAmount(content + modifier)
				end
				if Mypart == "Muffler" and item == Mypart then
					local condition = part:getCondition()
					if modifier > 0 then
                    	playerChar:Say(Viewer .. getText("UI_mufflerBonus") .. " " .. modifier)
					else
                    	playerChar:Say(Viewer .. getText("UI_mufflerMalus") .. " " .. modifier)
					end
					part:setCondition(condition + modifier)
				end
				if Mypart == "Battery" and item == Mypart then
					local condition = part:getCondition()
					if modifier > 0 then
                    	playerChar:Say(Viewer .. getText("UI_batteryBonus") .. " " .. modifier)
					else
                    	playerChar:Say(Viewer .. getText("UI_batteryMalus") .. " " .. modifier)
					end
					part:setCondition(condition + modifier)
				end
			end
		end
	end
end

--gifts event actions
function TWE_Events.GiftItems(event)
	local player = event.player
	local username = player:getUsername()
	local inv = player:getInventory()
	local Helpmeitem = 0
	local Trollmeitem = 0
	if event.message then
		player:Say(event.message)
	end

	if event.whatkind == 1 then
		----positive items table
		-- local HelpTheStreamer ={ "Base.BaseballBat", "Base.HuntingKnife", "Base.Axe", "Base.WristWatch_Right_DigitalRed", "Base.Crowbar", "Base.HandAxe", "Base.Burger", "Base.Crisps", "Base.Sandwich", "Base.BeerBottle", "Base.Pop","Base.Belt2","Base.TinnedBeans" }
		-- Helpmeitem = ZombRand(1,14)
		-- get the size of AshenTwitchEvents.HelpTheStreamer
		-- get a random number between 1 and the size of AshenTwitchEvents.HelpTheStreamer
		local length = 0
		-- TMP B42 FIX
		-- for k, v in pairs(AshenTwitchEvents.HelpTheStreamer) do
		for k, v in pairs(AshenTwitchEvents.HelpTheStreamer) do
			length = length + 1
		end
		length = length + 1
		Helpmeitem = ZombRand(1,length)

		-- inv:AddItem(HelpTheStreamer[Helpmeitem])
		inv:AddItem(AshenTwitchEvents.HelpTheStreamer[Helpmeitem])
		-- inv:AddItem(AshenTwitchEvents.HelpTheStreamer[Helpmeitem])
		if event.rolled then
			player:Say(event.rolled .. "ricevi un " .. getItemNameFromFullType(AshenTwitchEvents.HelpTheStreamer[Helpmeitem]))
		else
			player:Say(ViewerName .. " ".. getText("UI_HelpMEEvent") .. getItemNameFromFullType(AshenTwitchEvents.HelpTheStreamer[Helpmeitem]))
		end

		if initiator ~= username then
			args = {}
			args.message = username .. " ha ricevuto " .. getItemNameFromFullType(AshenTwitchEvents.HelpTheStreamer[Helpmeitem])
			args.initiator = initiator
			sendClientCommand("AshenTwitch", "ForwardMessage", args)
		end
	elseif event.whatkind == 2 then
		----negative items table
		-- local TrollTheStreamer = { "Base.Generator", "Base.LogStacks4", "Base.Dirtbag", "Base.Sandbag" }
		-- Trollmeitem = ZombRand(1,5)
		-- get the size of AshenTwitchEvents.TrollTheStreamer
		-- get a random number between 1 and the size of AshenTwitchEvents.TrollTheStreamer
		local length = 0
		-- TMP B42 FIX
		-- for k, v in pairs(AshenTwitchEvents.TrollTheStreamer) do
		for k, v in pairs(AshenTwitchEvents.TrollTheStreamer) do
			length = length + 1
		end
		length = length + 1
		Trollmeitem = ZombRand(1,length)

		-- inv:AddItem(TrollTheStreamer[Trollmeitem])
		inv:AddItem(AshenTwitchEvents.TrollTheStreamer[Trollmeitem])
		player:Say(ViewerName .. " " .. getText("UI_HelpMEEvent") .. getItemNameFromFullType(AshenTwitchEvents.TrollTheStreamer[Trollmeitem]) .. getText("UI_HelpMEETroll"))

		if initiator ~= username then
			args = {}
			args.message = username .. " ha ricevuto " .. getItemNameFromFullType(AshenTwitchEvents.TrollTheStreamer[Trollmeitem])
			args.initiator = initiator
			sendClientCommand("AshenTwitch", "ForwardMessage", args)
		end
	elseif event.whatkind == 3 then
		-- Trollmeitem = ZombRand(1,5)
		-- get the size of AshenTwitchEvents.TrollTheStreamer
		-- get a random number between 1 and the size of AshenTwitchEvents.TrollTheStreamer
		local length = 0
		for k, v in pairs(AshenTwitchEvents.TrollTheStreamer) do
			length = length + 1
		end
		length = length + 1
		Trollmeitem = ZombRand(1,length)
		
		-- Helpmeitem = ZombRand(1,14)
		-- get the size of AshenTwitchEvents.HelpTheStreamer
		-- get a random number between 1 and the size of AshenTwitchEvents.HelpTheStreamer
		local length = 0
		for k, v in pairs(AshenTwitchEvents.HelpTheStreamer) do
			length = length + 1
		end
		length = length + 1
		Helpmeitem = ZombRand(1,length)

		-- inv:AddItem(TrollTheStreamer[Trollmeitem])
		-- inv:AddItem(HelpTheStreamer[Helpmeitem])
		-- Ggift = HelpTheStreamer[Helpmeitem]
		-- Bgift = TrollTheStreamer[Trollmeitem]
		Ggift = AshenTwitchEvents.HelpTheStreamer[Helpmeitem]
		Bgift = AshenTwitchEvents.TrollTheStreamer[Trollmeitem]
		inv:AddItem(Ggift)
		inv:AddItem(Bgift)
		player:Say("So a " .. getItemNameFromFullType(Ggift) .. " with a " .. getItemNameFromFullType(Bgift) .. "! You have strange tastes " .. ViewerName .."!")

		if initiator ~= username then
			args.message = username .. " ha ricevuto " .. getItemNameFromFullType(Ggift) .. " e " .. getItemNameFromFullType(Bgift)
			args.initiator = initiator
			sendClientCommand("AshenTwitch", "ForwardMessage", args)
		end
	elseif event.whatkind == 4 and event.itemid then
		-- inv:AddItem(LocalEventsTable["title"])
		inv:AddItem(AshenTwitchEvents.HelpTheStreamer[event.itemid])
		player:Say(ViewerName .. " ".. getText("UI_HelpMEEvent") .. getItemNameFromFullType(AshenTwitchEvents.HelpTheStreamer[event.itemid]))
	end
end

-- function checkCharStatus()
AshenTwitchEvents.client.checkCharStatus = function()
	local player = getSpecificPlayer(0)
	local stats = player:getStats()
	-- check endurance
	local endurance_level = stats:getEndurance()
	local refresh = false
	if endurance_level < 0.6 then 
		stats:setEndurance(0.8)
		refresh = true
	end

	local fatigue_level = stats:getFatigue()
	if fatigue_level > 0.6 then
		 stats:setFatigue(0.4)
		 refresh = true
	end

	if refresh then
		player:Say("L'adrenalina del combattimento ti ha rinvigorito!")
	end
end

-- function performRolledEvent(reward)
AshenTwitchEvents.client.performRolledEvent = function(reward)
	local playerZero = getSpecificPlayer(0)
	local inv = playerZero:getInventory()
	local roll = ZombRand(1, 21)
	local event = {}
	local message = reward.Viewer .. " rolla " .. roll .. ": "
	reward.type = reward.type or 'good'
	if roll == 1 then
		-- spawn a horde
		if reward.type == 'good' then
			playerZero:Say(message .. "EVENTO GRANDE ORDA")
			event.from = reward.Viewer
			event.horde = true
			event.zedquant = AshenTwitchEvents.hordeZedQnt
			event.zedpacks = 5
			event.radius = 20
			event.type = 'zombie_spawn'
			AshenTwitchEvents.client.performAAIevent(event)
			AshenTwitchEvents.client.checkCharStatus()
		else
			-- gift from sandbox variable
			local item = AshenTwitchEvents.roll20Gift
			inv:AddItem(item)
			playerZero:Say(message .. "ricevi un " .. getItemNameFromFullType(item))
			if AshenTwitchEvents.Options.playSounds then
				playerZero:playSound("Thank")
			end
		end
	elseif roll == 20 then -- 20
		if reward.type == 'good' then
			-- gift from sandbox variable
			local item = AshenTwitchEvents.roll20Gift
			inv:AddItem(item)
			playerZero:Say(message .. "ricevi un " .. getItemNameFromFullType(item))
			if AshenTwitchEvents.Options.playSounds then
				playerZero:playSound("Thank")
			end
		else
			playerZero:Say(message .. "EVENTO GRANDE ORDA")
			event.from = reward.Viewer
			event.horde = true
			event.zedquant = AshenTwitchEvents.hordeZedQnt
			event.zedpacks = 5
			event.radius = 20
			event.type = 'zombie_spawn'
			AshenTwitchEvents.client.performAAIevent(event)
			AshenTwitchEvents.client.checkCharStatus()
		end
	elseif roll <= 6 then
		playerZero:Say(message .. "nessun effetto")
		if AshenTwitchEvents.Options.playSounds then
			playerZero:playSound("Mario")
		end
	-- elseif roll % 2 == 1 then -- numeri dispari -> spawn zombie
	elseif reward.type == 'evil' then
		-- get integer of the roll divided by 6
		local effects_n = math.floor(roll / 6)
		for i = 1, effects_n+1 do
			local effect = ZombRand(1, 11)
			if effect <= 5 then
				-- 1 zombie spawn
				-- basic effect
				event.from = reward.Viewer
				event.type = 'zombie_spawn'
				event.zedquant = ZombRand(1, 3)
				event.zedpacks = ZombRand(1, 3)
				AshenTwitchEvents.client.performAAIevent(event)
				if i > 1 then
					message = message .. "+"
				end
				message = message .. "SPAWN(" .. event.zedquant * event.zedpacks .. ")"
			elseif effect <= 7 then
				-- 2 negative 
				local length = 0
				for k, v in pairs(AshenTwitchEvents.TWETraitsTable) do
					length = length + 1
				end
				length = length + 1
				event = {}
				event.player = playerZero
				event.trait = ZombRand(1,length)
				event.initiator = playerZero:getUsername()
				AshenTwitchEvents.client.TWETableTraitsTrigger(event)
				if i > 1 then
					message = message .. "+"
				end
				message = message .. "TRAIT"
			elseif effect <= 9 then
				-- 3 drunk
				event = {}
				event.player = playerZero
				event.whatkind = 1
				event.initiator = playerZero:getUsername()
				TWE_Events.PlayerModifier(event)
				if i > 1 then
					message = message .. "+"
				end
				message = message .. "BEVI"
			elseif effect == 10 then
				-- 4 teleport player
				event = {}
				event.player = playerZero
				event.whatkind = 3
				event.initiator = playerZero:getUsername()
				TWE_Events.PlayerModifier(event)
				if i > 1 then
					message = message .. "+"
				end
				message = message .. "TELEPORT"
			end
		end
		playerZero:Say(message)
	else -- 10,12,14,16,18 // reward.type == 'good'
		-- get integer of the roll divided by 6
		local effects_n = math.floor(roll / 6)
		for i = 1, effects_n+1 do
			local effect = ZombRand(1, 6)
			if  effect <= 3 then
				-- item gift
				event = {}
				event.player = playerZero
				event.initiator = playerZero:getUsername()
				event.whatkind = 1
				event.rolled = ""
				TWE_Events.GiftItems(event)
				if i > 1 then
					message = message .. "+"
				end
				message = message .. "ITEM"
			elseif effect == 4 then
				-- 4 more endurance
				event = {}
				event.player = playerZero
				event.whatkind = 14
				event.initiator = playerZero:getUsername()
				TWE_Events.PlayerModifier(event)
				if i > 1 then
					message = message .. "+"
				end
				message = message .. "RESISTENZA"
			elseif effect == 5 then
				-- weaken zombie to 1hp
				TWE_Events.ZombieModifier(1, playerZero:getUsername())
				message = message .. "ZOMBIE1HP"
			end
		end
		playerZero:Say(message)
	end
end

--zombie modifier event actions
function TWE_Events.ZombieModifier(whatkind, initiator)
    local player = getPlayer()
    local zombieList = player:getCell():getZombieList()
    local zombie
    local amount = zombieList:size()
    if amount == 0 then return false end

	if whatkind == 1 then
		-- weaken zombies
		for i=0, zombieList:size()-1 do
			zombie = zombieList:get(i)
			zombie:setHealth(0.01)
		end
	
		player:playSoundLocal("zombiehit2")
		player:Say(ViewerName .. " indebolisce " .. amount .. " zombie!")
	elseif whatkind == 2 then
		-- teleport zombies around the player
		local x, y, z, tile
		local cell = player:getCell()
		for i=0, zombieList:size()-1 do
			zombie = zombieList:get(i)
			tile = cell:getRandomOutdoorTile()
			x = tile:getX()
			y = tile:getY()
			z = tile:getZ()
			zombie:setX(x)
			zombie:setY(y)
			zombie:setZ(z)
		end

		player:playSoundLocal("zombiehit1")
		player:Say(ViewerName .. " teletrasporta gli zombie!")
	elseif whatkind == 3 then
		-- fast zombies
		zombieList = player:getCell():getZombieList()
		for i=0, zombieList:size()-1 do
			zombie = zombieList:get(i)
			zombie:setCanWalk(true)
			zombie:setCrawler(false)
			local oldSpeed = getSandboxOptions():getOptionByName("ZombieLore.Speed")
			oldSpeed = oldSpeed:getValue()
			getSandboxOptions():set("ZombieLore.Speed", 4)
			zombie:makeInactive(true)
			zombie:makeInactive(false)
			zombie:DoZombieStats()
			getSandboxOptions():set("ZombieLore.Speed",oldSpeed)
		end
	
		player:playSoundLocal("zombiehit4")
		player:Say(ViewerName .. " rende " .. amount .. " zombie CORRIDORI!")
	elseif whatkind == 4 then
		-- slow zombies
		zombieList = player:getCell():getZombieList()
		for i=0, zombieList:size()-1 do
			zombie = zombieList:get(i)
			zombie:setCanWalk(true)
			zombie:setCrawler(false)
			local oldSpeed = getSandboxOptions():getOptionByName("ZombieLore.Speed")
			oldSpeed = oldSpeed:getValue()
			getSandboxOptions():set("ZombieLore.Speed", 0.1)
			zombie:makeInactive(true)
			zombie:makeInactive(false)
			zombie:DoZombieStats()
			getSandboxOptions():set("ZombieLore.Speed",oldSpeed)
		end
		
		player:playSoundLocal("zombiehit4")
		player:Say(ViewerName .. " rende " .. amount .. " zombie LENTI!")
	end
end

function TWE_Events.ZombieModifierEnd()
	local calendar = PZCalendar.getInstance()
	if calendar:getTimeInMillis() > temporaryZombiesEnd then
		if isClient() then
			if temporaryZombies then
				for k, v in pairs(temporaryZombies) do
					v:Kill(v)
					-- zombie:removeFromWorld()
				end
			end
			temporaryZombies = {}
		end
		temporaryZombiesEnd = 0
		Events.EveryOneMinute.Remove(TWE_Events.ZombieModifierEnd)

		local player = getPlayer()
		if not player then return end
		player:Say("Questi zombie erano dei corridori della domenica...")
	end
end

function TWE_Events.Jumpscare()
    local player = getPlayer()
    local x = player:getX()
    local y = player:getY()
    local z = player:getZ()
    local square = player:getSquare()

    getSoundManager():PlayWorldSound("ZombieSurprisedPlayer", square, 0, 5, 5, false);
    addSound(player, x, y, z, 150, 50);

    local messages = { "BUONGIORNO MIO CARO VICINO!", "SIKAKA", "DOVE HAI MESSO LA NUTELLA?!?", "LA CHIAVE LUG!" }
    local choice = messages[ZombRand(1, 3)]
    player:setCanShout(true)
    player:SayShout(choice)
    -- player:Say(ViewerName .. " zombie ti colga!")
end

--player modifier event actions
function TWE_Events.PlayerModifier(event)
	local player = event.player
	local stats = player:getStats()
	local whatkind = event.whatkind
	local initiator = event.initiator
	local message = event.message

	if whatkind == 1 then -- +40% drunkenness
		local drunk_level = stats:getDrunkenness()
		local new_level = drunk_level + 40
		if new_level > 80 then new_level = 80 end
		stats:setDrunkenness(new_level)
		player:Say(ViewerName .. " ci offre una birra!")
	elseif whatkind == 2 then -- +20% hunger
		local hunger_level = stats:getHunger()
		local new_level = hunger_level + 0.2
		if new_level > 0.6 then new_level = 0.6 end
		stats:setHunger(new_level)
		player:Say(ViewerName .. " dice che sentiamo un languorino!")
	elseif whatkind == 3 then
		local cell = player:getCell()
		local tile = cell:getRandomOutdoorTile()
		local x = tile:getX()
		local y = tile:getY()
		local z = tile:getZ()
		local range = event.range
		
		player:setPosition(x, y, z)
		player:Say(ViewerName .. " mi ha teletrasportato!")
	elseif whatkind == 4 then -- -20% endurance
		local endurance_level = stats:getEndurance()
		local new_level = endurance_level - 0.2
		if new_level < 0 then new_level = 0 end
		stats:setEndurance(new_level)
		player:Say(ViewerName .. " ci fa sentire affaticati!")
	elseif whatkind == 5 then -- +20% fatigue
		local fatigue_level = stats:getFatigue()
		local new_level = fatigue_level + 0.2
		if new_level > 1 then new_level = 1 end
		stats:setFatigue(new_level)
		player:Say(ViewerName .. " ci fa sentire assonnati!")
	elseif whatkind == 8 then -- drop hand items
		player:dropHandItems()
		player:Say(ViewerName .. " ci fa cadere tutto dalle mani!")
	elseif whatkind == 14 then -- +20% endurance
		local endurance_level = stats:getEndurance()
		local new_level = endurance_level + 0.2
		if new_level > 1 then new_level = 1 end
		stats:setEndurance(new_level)
		player:Say(ViewerName .. " ci dona forze!")
	elseif whatkind == 15 then -- -20% fatigue
		local fatigue_level = stats:getFatigue()
		local new_level = fatigue_level - 0.2
		if new_level < 0 then new_level = 0 end
		stats:setFatigue(new_level)
		player:Say(ViewerName .. " ci dona riposo!")
	elseif whatkind == 21 then -- shout a message
		player:setCanShout(true)
		player:SayShout(message)
		
		local x = player:getX()
		local y = player:getY()
		local z = player:getZ()
		local range = event.range
		addSound(player, x, y, z, range, 50) -- Genera un suono udibile dagli zombie
	-- elseif whatkind == 31 then -- force run
	-- 	player:setForceRun(true)
	-- 	player:setForceSprint(true)
	-- elseif whatkind == 32 then -- force run
	-- 	player:setForceRun(false)
	-- 	player:setForceSprint(false)
	end
end

--environment modifier event actions
function TWE_Events.EnvironmentModifier(whatkind, initiator)
	return
end

--spawn x,y,z randomizer needs improvement
-- function SpawnLoc(player, maxValue)
AshenTwitchEvents.client.SpawnLoc = function(player, maxValue)
    -- local mx = getPlayer():getX();
    -- local my = getPlayer():getY();
    -- local mz = getPlayer():getZ();
    local mx = player:getX();
    local my = player:getY();
    local mz = player:getZ();
    --local DistOffset = ZombRand(40,85);
    -- local DistOffset = ZombRand(10,maxValue);
    -- local DistOffset = maxValue;
	-- local Operation = ZombRand(1,5);
    -- local logic ={
    --     function() mx = mx + DistOffset end,
    --     function() mx = mx - DistOffset end,
    --     function() my = my + DistOffset end,
    --     function() my = my - DistOffset end
    -- }
    -- logic[Operation]()
    local angle = ZombRandFloat(0, 2 * math.pi)
    local distance = maxValue
    local mx = mx + math.cos(angle) * maxValue
    local my = my + math.sin(angle) * maxValue
    return mx,my,mz
end

ServerCommands.AshenTwitch.Handshake = function(args)
	if not isClient() then 
		AshenTwitchEvents.HelpTheStreamer = SandboxVars.AshenTwitchEvents.HelpTheStreamer
		AshenTwitchEvents.TrollTheStreamer = SandboxVars.AshenTwitchEvents.TrollTheStreamer
		AshenTwitchEvents.TWE_Airevents = SandboxVars.AshenTwitchEvents.TWE_Airevents
		AshenTwitchEvents.TWETraitsTable = SandboxVars.AshenTwitchEvents.TWETraitsTable
	else
		AshenTwitchEvents.HelpTheStreamer = args.sandbox.HelpTheStreamer
		AshenTwitchEvents.TrollTheStreamer = args.sandbox.TrollTheStreamer
		AshenTwitchEvents.TWE_Airevents = args.sandbox.TWE_Airevents
		AshenTwitchEvents.TWETraitsTable = args.sandbox.TWETraitsTable
	end

	playerChar = getPlayer()
	-- print('------------=Twitch Events: Handshake=------------', args.initiator, args.state)
	if args.state == "Accepted" then
		-- print("--TWEEVENT- Handshake ACCEPTED -- " .. args.initiator)
		-- perform the event
		if AshenTwitchEvents.Options.acceptEvents or playerChar:getUsername() == args.initiator then
			-- print("accepting events", AshenTwitchEvents.Options.acceptEvents)
			-- print("player is initiator", playerChar:getUsername() == args.initiator)
			AshenTwitchEvents.client.performEvent(args.EventsTable, args.initiator)
		end

		-- if playerChar:getUsername() == args.initiator then
		-- 	print("mio eventooo")
		-- end
		-- args.state = "Join"
		-- sendClientCommand("AshenTwitch", "Handshake", args); -- Trigger Event from Client to Server
	-- elseif result.state == "Execute" then
	-- 	print("--TWEEVENT- Handshake ACCEPTED -- " .. args.initiator)
	end
end


ServerCommands.AshenTwitch.ForwardMessage = function(args)
	playerChar = getPlayer()
	if args.initiator == playerChar:getUsername() then
		playerChar:Say(args.message)
	end
end


-- local onServerCommand = function(module, command, args) -- Events Constructor.
AshenTwitchEvents.client.onServerCommand = function(module, command, args) -- Events Constructor.
    if ServerCommands[module] and ServerCommands[module][command] then
	    ServerCommands[module][command](args)
    end
end

if isClient() then
	Events.OnServerCommand.Add(AshenTwitchEvents.client.onServerCommand)
end

return TWE_Events