require "ExpandedHelicopter02a_Presets"
require "ExpandedHelicopter09_EasyConfigOptions"

AshenTwitchEvents = AshenTwitchEvents or {}
AshenTwitchEvents.HelpTheStreamer = {}
AshenTwitchEvents.TrollTheStreamer = {}
AshenTwitchEvents.TWE_Airevents = {}
AshenTwitchEvents.TWETraitsTable = {}

local timervalue = 10 --timer value in minutes for the temporary traits
local TWE_Events = {}
local TraitEndTime = 0
local ViewerName = ""
----positive items table
local HelpTheStreamer ={ "Base.BaseballBat", "Base.HuntingKnife", "Base.Axe", "Base.WristWatch_Right_DigitalRed", "Base.Crowbar", "Base.HandAxe", "Base.Burger", "Base.Crisps", "Base.Sandwich", "Base.BeerBottle", "Base.Pop","Base.Belt2","Base.TinnedBeans" }
----negative items table
local TrollTheStreamer = { "Base.Generator", "Base.LogStacks4", "Base.Dirtbag", "Base.Sandbag" }
-----Air Events Presets
local TWE_Airevents = {"military","police","news_chopper","raiders","FEMA_drop","jet","survivor_heli"}
-----Temporary traits table
local TWETraitsTable = {[1]="Deaf",[2]="Thinskinned",[3]="AllThumbs",[4]="Cowardly",[5]="Hemophobic",[6]="SundayDriver",[7]="Graceful",[8]="KeenHearing",[9]="ThickSkinned",[10]="SpeedDemon",[11]="Jogger",[12]="Inconspicuous"}
local TWETempTraitsTable = {}
local TWEAnnouceEvents = true
local playerChar = getPlayer()
local LocalEventsTable = {}


--processes the EventsTable generated by getreward
function performHandshake(EventsTable)
    local playerChar = getPlayer()
	-- LocalEventsTable = EventsTable
	-- print(playerChar:getUsername())
	ServerEvent = {["Etype"] = "Handshake", ["ZedX"] = Zedx, ["ZedY"] = Zedy, ["ZedQ"] = zedquant, ["target"] = playerchar, ["initiator"] = playerChar:getUsername(), ["EventsTable"] = EventsTable}
	ServerEvent.state = "Request"
	--playerChar:Say("x:" .. tostring(ServerEvent.ZedX) .. "y: " .. tostring(ServerEvent.ZedY))
	sendClientCommand("TWEEvents", "Handshake", ServerEvent); -- Trigger Event from Client to Server
end

function performEvent(EventsTable, initiator)
	local playerChar = getPlayer()
	if EventsTable then
		ViewerName = EventsTable["Viewer"]
		if EventsTable["zombies"] == true and EventsTable["zedquant"] > 0 and initiator == playerChar:getUsername() then
			print("------------=Twitch Events: zombies=------------")
			if TWEAnnouceEvents == true then
				playerChar:Say(EventsTable["Viewer"] .. " sent " ..EventsTable["zedquant"] .. " zombies")
			end

			--local Zedx, Zedy, wz = LSpawnLoc();
			local zedquant = tonumber(EventsTable["zedquant"])
			if isClient() then
				local Zedx, Zedy, Zedz = SpawnLoc(50)
				ServerEvent = {["Etype"] = "Zedspawn", ["ZedX"] = Zedx, ["ZedY"] = Zedy, ["ZedQ"] = zedquant, ["PlayerChar"] = playerchar }
				--playerChar:Say("x:" .. tostring(ServerEvent.ZedX) .. "y: " .. tostring(ServerEvent.ZedY))
				sendClientCommand("TWEEvents", "Zedspawn", ServerEvent); -- Trigger Event from Client to Server
			else
				local Zedx, Zedy, Zedz = SpawnLoc(85)
				createHordeFromTo(Zedx, Zedy, playerChar:getX(), playerChar:getY(), zedquant)
			end
		end

		if tonumber(EventsTable["gifts"]) > 0 then
			print("------------=Twitch Events: gift =------------")
			TWE_Events.GiftItems(tonumber(EventsTable["gifts"]))
		end

		if tonumber(EventsTable["helicopter"]) > 0 and initiator == playerChar:getUsername() then

			if tonumber(EventsTable["helicopter"]) == 1 then
				print("------------=Twitch Events: Air Event=------------")
				if TWEAnnouceEvents == true then
					playerChar:Say(EventsTable["Viewer"] .. " called a Military Heli")
				end
				if isClient() then
					ServerEvent = {["Etype"] = "AirEvent", ["target"] = playerchar, ["Event"] = "military" }
					sendClientCommand("TWEEvents", "AirEvent", ServerEvent); -- Trigger Event from Client to Server
				else
					local heli = getFreeHelicopter("military")
					heli:launch(playerChar, false)
				end
			end



			if tonumber(EventsTable["helicopter"]) == 2 then
				print("------------=Twitch Events: Air Event=------------")
				if TWEAnnouceEvents == true then
					playerChar:Say(EventsTable["Viewer"] .. " called a News Heli")
				end
				if isClient() then
					ServerEvent = {["Etype"] = "AirEvent", ["target"] = playerchar, ["Event"] = "news_chopper" }
					sendClientCommand("TWEEvents", "AirEvent", ServerEvent); -- Trigger Event from Client to Server
				else
					local heli = getFreeHelicopter("military")
					heli:launch(playerChar, false)
				end
			end


			if tonumber(EventsTable["helicopter"]) == 3 then
				print("------------=Twitch Events: Air Event=------------")
				if TWEAnnouceEvents == true then
					playerChar:Say(EventsTable["Viewer"] .. " called a Police Heli")
				end
				if isClient() then
					ServerEvent = {["Etype"] = "AirEvent", ["target"] = playerchar, ["Event"] = "police" }
					sendClientCommand("TWEEvents", "AirEvent", ServerEvent); -- Trigger Event from Client to Server
				else
					local heli = getFreeHelicopter("police")
					heli:launch(playerChar, false)
				end
			end


			if tonumber(EventsTable["helicopter"]) == 4 then
				print("------------=Twitch Events: Air Event=------------")
				if TWEAnnouceEvents == true then
					playerChar:Say(EventsTable["Viewer"] .. " called a Raiders Heli")
				end
				if isClient() then
					ServerEvent = {["Etype"] = "AirEvent", ["target"] = playerchar, ["Event"] = "raiders" }
					sendClientCommand("TWEEvents", "AirEvent", ServerEvent); -- Trigger Event from Client to Server
				else
					local heli = getFreeHelicopter("raiders")
					heli:launch(playerChar, false)
				end
			end


			if tonumber(EventsTable["helicopter"]) == 5 then
				print("------------=Twitch Events: Air Event=------------")
				if TWEAnnouceEvents == true then
					playerChar:Say(EventsTable["Viewer"] .. " called a FEMA drop")
				end
				if isClient() then
					ServerEvent = {["Etype"] = "AirEvent", ["target"] = playerchar, ["Event"] = "FEMA_drop" }
					sendClientCommand("TWEEvents", "AirEvent", ServerEvent); -- Trigger Event from Client to Server
				else
					local heli = getFreeHelicopter("FEMA_drop")
					heli:launch(playerChar, false)
				end
			end


			if tonumber(EventsTable["helicopter"]) == 6 then
				print("------------=Twitch Events: Air Event=------------")
				if TWEAnnouceEvents == true then
					playerChar:Say(EventsTable["Viewer"] .. " called a jet")
				end
				if isClient() then
					ServerEvent = {["Etype"] = "AirEvent", ["target"] = playerchar, ["Event"] = "jet" }
					sendClientCommand("TWEEvents", "AirEvent", ServerEvent); -- Trigger Event from Client to Server
				else
					local heli = getFreeHelicopter("jet")
					heli:launch(playerChar, false)
				end
			end


			if tonumber(EventsTable["helicopter"]) == 7 then
				print("------------=Twitch Events: Air Event=------------")
				if TWEAnnouceEvents == true then
					playerChar:Say(EventsTable["Viewer"] .. " called a random air event")
				end
				if isClient() then
					ServerEvent = {["Etype"] = "AirEvent", ["target"] = playerchar, ["Event"] = "RANDOM" }
					sendClientCommand("TWEEvents", "AirEvent", ServerEvent); -- Trigger Event from Client to Server
				else
					local heli = getFreeHelicopter("RANDOM")
					heli:launch(playerChar, false)
				end
			end

			if tonumber(EventsTable["helicopter"]) == 69 then
				print("------------=Twitch Events: Custom Air Event=------------")
				if TWEAnnouceEvents == true then
					playerChar:Say(EventsTable["Viewer"] .. " called a ".. EventsTable["title"])
				end
				if isClient() then
					ServerEvent = {["Etype"] = "AirEvent", ["target"] = playerchar, ["Event"] = EventsTable["title"] }
					sendClientCommand("TWEEvents", "AirEvent", ServerEvent); -- Trigger Event from Client to Server
				else
					local heli = getFreeHelicopter(EventsTable["title"])
					heli:launch(playerChar, false)
				end
			end
			
		end

		if EventsTable["gas"] == "true" then --car events begin
			TWE_Events.TWECars("GasTank")
		end
		if EventsTable["tire"] == "true" then
			TWE_Events.TWECars("FlatTire")
		end
		if EventsTable["muffler"] == "true" then
			TWE_Events.TWECars("Muffler")
		end
		if EventsTable["battery"] == "true" then
			TWE_Events.TWECars("Battery")
		end
		if EventsTable["engine"] == "true" then -- car events end
			TWE_Events.TWECars("Engine")
		end
		if tonumber(EventsTable["trait"]) > 0 then -- traits begin
			print("------------=Twitch Events: trait Event=------------")
			TWETableTraitsTrigger(tonumber(EventsTable["trait"]))
		end
	end
end

--temporary traits trigger---
function TWETableTraitsTrigger(MyTrait)
		local playerChar = getPlayer()
		local calendar = PZCalendar.getInstance()
		local hour = calendar:get(Calendar.HOUR_OF_DAY)
		local minute = calendar:get(Calendar.MINUTE)
		local second = calendar:get(Calendar.SECOND)
		if hour == 0 then --check if its 0, if true replaces 0 with 24
		TraitEndTime = (24 * 60 + minute + timervalue ) * 60 + second
		else TraitEndTime = (hour * 60 + minute + timervalue) * 60 + second
		end	
		if not playerChar:HasTrait(TWETraitsTable[MyTrait]) then
        playerChar:getTraits():add(TWETraitsTable[MyTrait]);
		table.insert(TWETempTraitsTable, {trait = TWETraitsTable[MyTrait], endtime = TraitEndTime})
		HaloTextHelper.addTextWithArrow(playerChar, getText("UI_trait_"..TWETraitsTable[MyTrait]), true, HaloTextHelper.getColorGreen())
        Events.EveryOneMinute.Remove(TWE_TraitCheck);
        Events.EveryOneMinute.Add(TWE_TraitCheck);
    end
end
--temporary traits timer check---
function TWE_TraitCheck()
		local playerChar = getPlayer()
		local calendar = PZCalendar.getInstance()
		local hour = calendar:get(Calendar.HOUR_OF_DAY)
		local minute = calendar:get(Calendar.MINUTE)
		local second = calendar:get(Calendar.SECOND)
		if hour == 0 then --check if its 0, if true replaces 0 with 24
		currentTime = (24 * 60 + minute) * 60 + second
		else currentTime = (hour * 60 + minute) * 60 + second
		end	
        for i, v in ipairs(TWETempTraitsTable) do
        local trait = v.trait
        local endtime = v.endtime
        if endtime <= currentTime then
			print("Removing trait: " .. trait)
			print("Endtime: " .. endtime)
			playerChar:getTraits():remove(trait);
            HaloTextHelper.addTextWithArrow(playerChar, getText("UI_trait_"..trait), false, HaloTextHelper.getColorRed())     
            table.remove(TWETempTraitsTable, i)
            if TWETempTraitsTable == 0 then
                Events.EveryOneMinute.Remove(TWE_TraitCheck)
                break
            end
        end
		end

end
--car event actions
function TWE_Events.TWECars(Mypart)
    local playerChar = getPlayer()
	local mycar = playerChar:getVehicle()
    local TireSet = { "TireRearRight", "TireRearLeft"," TireFrontRight", "TireFrontLeft"}
    local WhichTire = ZombRand(1,5)
    if mycar ~= nil then
        for i = mycar:getPartCount()-1,0,-1 do
            local part = mycar:getPartByIndex(i)
            local cat = part:getCategory()
            local item = part:getId()
            if item ~=  nil then
                if Mypart == "Engine" and item == Mypart then
                    playerChar:Say("No no no... don't die on me now!!")
					part:setCondition(0)
                end
                if Mypart == "FlatTire" then
                    if TireSet[WhichTire] == item then
                        VehicleUtils.RemoveTire(part, true)
                    end
                    end
                end
                if Mypart == "GasTank" and item == Mypart then
                part:setContainerContentAmount(0)
                end
                if Mypart == "Muffler" and item == Mypart then
                part:setCondition(0)
                end
                if Mypart == "Battery" and item == Mypart then
                part:setCondition(0)
                end
            end
        end
end
--gifts event actions
function TWE_Events.GiftItems(whatkind)
local player = getSpecificPlayer(0)
local inv = player:getInventory()
local Helpmeitem = 0
local Trollmeitem = 0
	if whatkind == 1 then
		Helpmeitem = ZombRand(1,14)
		inv:AddItem(HelpTheStreamer[Helpmeitem])
		player:Say("Thank you for the " .. getItemNameFromFullType(HelpTheStreamer[Helpmeitem]) .. " " .. ViewerName)
	elseif whatkind == 2 then
		Trollmeitem = ZombRand(1,5)
		inv:AddItem(TrollTheStreamer[Trollmeitem])
		player:Say("Uau... a " .. getItemNameFromFullType(TrollTheStreamer[Trollmeitem]).. " " .. ViewerName .. " really?!")
	elseif whatkind == 3 then
		Trollmeitem = ZombRand(1,5)
		inv:AddItem(TrollTheStreamer[Trollmeitem])
		Helpmeitem = ZombRand(1,14)
		inv:AddItem(HelpTheStreamer[Helpmeitem])
		Ggift = HelpTheStreamer[Helpmeitem]
		Bgift = TrollTheStreamer[Trollmeitem]
		player:Say("So a " .. getItemNameFromFullType(HelpTheStreamer[Helpmeitem]) .. " with a " .. getItemNameFromFullType(TrollTheStreamer[Trollmeitem]) .. "! You have strange tastes " .. ViewerName .."!")
	elseif whatkind == 4 then
		inv:AddItem(LocalEventsTable["title"])	
		end
end

--spawn x,y,z randomizer needs improvement
function SpawnLoc(maxValue)
    local mx = getPlayer():getX();
    local my = getPlayer():getY();
    local mz = getPlayer():getZ();
    --local DistOffset = ZombRand(40,85);
    local DistOffset = ZombRand(25,maxValue);
	local Operation = ZombRand(1,5);
    local logic ={
        function() mx = mx + DistOffset end,
        function() mx = mx - DistOffset end,
        function() my = my + DistOffset end,
        function() my = my - DistOffset end
    }
    logic[Operation]()
    return mx,my,mz
end

function handshake(module, command, args)
    if module ~= "AshenTwitchEvents" or command ~= "Handshake" then
        return
    end

	playerChar = getPlayer()
	-- print('------------=Twitch Events: Handshake=------------', args.initiator, args.state)
	if args.state == "Accepted" then
		-- print("--TWEEVENT- Handshake ACCEPTED -- " .. args.initiator)
		-- performe the event
		print()
		if AshenTwitchEvents.Options.acceptEvents or playerChar:getUsername() == args.initiator then
			-- print("accepting events", AshenTwitchEvents.Options.acceptEvents)
			-- print("player is initiator", playerChar:getUsername() == args.initiator)
			performEvent(args.EventsTable, args.initiator)
		end

		-- if playerChar:getUsername() == args.initiator then
		-- 	print("mio eventooo")
		-- end
		-- args.state = "Join"
		-- sendClientCommand("TWEEvents", "Handshake", args); -- Trigger Event from Client to Server
	-- elseif result.state == "Execute" then
	-- 	print("--TWEEVENT- Handshake ACCEPTED -- " .. args.initiator)
	end
end

Events.OnServerCommand.Add(handshake)

return TWE_Events